### ISSUE TITLE
Event data body with escaped quotes

### ISSUE THREAD

**Issue by krofka** [prooph/event-store-http-client#35]
Hi,

I found the problem with $by_correlation_id in ES version 5, when using this library to append events through HTTP API (https://groups.google.com/forum/#!topic/event-store/1_e1yZfeWP0). The library sends json with escaped quotes in data and metadata, so the projection is not working.

Is it problem of the library or EventStore?

Thanks,
Jakub Koci

Edit: see also https://github.com/EventStore/EventStore/issues/1875

**Comment by krofka** [comment]
https://github.com/EventStore/EventStore/issues/1875

**Comment by krofka** [comment]
Problem was resolved in ES... https://github.com/EventStore/EventStore/issues/1875#issuecomment-469978459

**Comment by prolic** [comment]
Thanks for reporting @krofka
