### ISSUE TITLE
Suggestion: Improve ProjectionCommandFailed exception message

### ISSUE THREAD

**Issue by burzum** [prooph/event-store-http-client#39]
Would it be possible to either change this message and add a sentence like "Make sure your event store has projections enabled." Or even better throw a "ProjectionsNotEnabled" exception?

>Uncaught Prooph\EventStoreHttpClient\Exception\ProjectionCommandFailed: Server returned 404 (Not Found) for GET on /projection/TEST_PROJECTION/result in src\Projections\ProjectionsManager.php:541

**Comment by prolic** [comment]
We don't get more information than that from the event store server. All we know is that a 404 not found was returned

**Comment by burzum** [comment]
@prolic maybe add it as a question then to the end of the message? "Has your event store projections enabled?" It's a trap if you're not used to the store and projects. If you don't want to add it just close the ticket.
