### ISSUE TITLE
Schema inconsistency

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-http-client#4]
`ConnectionSettings` used by `EventStoreHttpConnection` has `$useSslConnection` parameter which is resolved to http or https [here](https://github.com/prooph/event-store-http-client/blob/da0648deb37ae9c35758f3b86fa76fe44865646b/src/Internal/EventStoreHttpConnection.php#L69).

`ProjectionsManagerFactory` on the other hand is using `EndpointExtensions` constants.

I expect you'll want to unify this somehow.

**Comment by prolic** [comment]
Yep, on my todo-list, should be `EndpointExtensions`. Wanna change yourself and provide a PR?

**Comment by enumag** [comment]
Maybe we shoul use `ConnectionSettings` in `ProjectionsManagerFactory`? But I'm not sure - it seems that `ProjectionsManagerFactory` doesn't need the `$requireMaster` boolean.

**Comment by prolic** [comment]
> Maybe we should use `ConnectionSettings` in `ProjectionsManagerFactory`? But I'm not sure - it seems that `ProjectionsManagerFactory` doesn't need the `$requireMaster` boolean.

Not sure about that.

**Comment by prolic** [comment]
Nope, this header makes no sense there, but that's not the main issue I have. We could have an option that is unused in the managers, I think that's not a big deal.
However for the QueryManager, you may need to configure your http client manually yourself to set much higher timeouts as the defaults.

**Comment by enumag** [comment]
> Nope, this header makes no sense there, but that's not the main issue I have. We could have an option that is unused in the managers, I think that's not a big deal.

Then we can change `ConnectionSettings` to use `EndpointExtensions` and use it in all the managers, right?

> However for the QueryManager, you may need to configure your http client manually yourself to set much higher timeouts as the defaults.

I'm not suggesting to add the HttpClient to ConnectionSettings. And there is nothing forcing you to configure everything the same way either so I don't see a problem here.

**Comment by enumag** [comment]
Hmm there are some more inconsistencies... Some classes (like `ProjectionsClient`) are using `EndpointExtensions::formatStringToHttpUrl()` while other classes such as `AppendToStreamOperation` are using simple string concatenation. I'm guessing this should be unified as well.

**Comment by prolic** [comment]
> Hmm there are some more inconsistencies... Some classes (like `ProjectionsClient`) are using `EndpointExtensions::formatStringToHttpUrl()` while other classes such as `AppendToStreamOperation` are using simple string concatenation. I'm guessing this should be unified as well.

Yes, most of the code was written quick and dirty - I expect lots of inconsistencies currently. I need to review everything once tests are there.
