### ISSUE TITLE
Fatal error in ProjectionDetails::__construct()

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-http-client#44]
```
TypeError:
Argument 9 passed to Prooph\EventStore\Projections\ProjectionDetails::__construct()
must be of the type string, null given, called in
/usr/app/vendor/prooph/event-store-http-client/src/Projections/ProjectionsManager.php
on line 522
```

**Comment by prolic** [comment]
Thanks, will look into it, or would you mind submitting a pull request?

**Comment by enumag** [comment]
I'm not exactly sure what's the proper fix here. Also I don't know how it happened and can't reproduce it. I just found it in the logs.

**Comment by prolic** [comment]
Most likely it should be `$entry['stateReason'] ?? ''` @ line 506 - that's just a guess, but I can imagine the stateReason is empty when status is OK-ish.
