### ISSUE TITLE
Client doesn't match event store interfaces?

### ISSUE THREAD

**Issue by burzum** [prooph/event-store-http-client#49]
The HTTP client doesn't match recent changes to the event store library?

> Fatal error: Could not check compatibility between Prooph\EventStoreHttpClient\Internal\EventStoreHttpConnection::subscribeToStream(string $stream, bool $resolveLinkTos, Prooph\EventStore\EventAppearedOnSubscription $eventAppeared, ?Prooph\EventStore\SubscriptionDropped $subscriptionDropped = NULL, ?Prooph\EventStore\UserCredentials $userCredentials = NULL): Prooph\EventStore\EventStoreSubscription and Prooph\EventStore\EventStoreConnection::subscribeToStream(string $stream, bool $resolveLinkTos, Closure $eventAppeared, ?Closure $subscriptionDropped = NULL, ?Prooph\EventStore\UserCredentials $userCredentials = NULL): Prooph\EventStore\EventStoreSubscription, because class Prooph\EventStore\SubscriptionDropped is not available in \event-sourcing-test-app\vendor\prooph\event-store-http-client\src\Internal\EventStoreHttpConnection.php on line 1090

**Comment by burzum** [comment]
Fixed in https://github.com/prooph/event-store-http-client/pull/50

**Comment by prolic** [comment]
Yes, it's a known issue
