### ISSUE TITLE
Common value objects

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-http-client#5]
For now I'll have to use both the HTTP client (for reading and appending to streams) and the TCP client (for connectToPersistentSubscription). So I need to be able to transform the `RecordedEvent` intances to real domain events in both modes.

It's easy to do of course, just slightly annoying since `RecordedEvent` is implemented in each client separately. There are quite a few other objects that appear in both of the libraries - it might make sense to share these between both libraries.

What do you think?

**Comment by prolic** [comment]
I was having the same thoughts. Maybe we can put common value objects in event-store v8?

**Comment by prolic** [comment]
do
