### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-http-client#7]
There are some undefined classes from `Prooph\EventStore\` namespace used in the code but they are not present in this package nor included as a composer dependency.

Example: https://github.com/prooph/event-store-http-client/blob/52947b07e2d569bc7c90e46f3c1928116c6f02c1/src/ClientOperations/PersistentSubscriptionOperations.php#L18-L21

**Comment by prolic** [comment]
Yep, that's a left-over from porting the code, I missed that.
